# Site settings
title: Hello, I am Sara.
subtitle: interesting
email: 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://konari.github.io"
github_username:  konari

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

analytics :
  provider : google
  google:
    tracking_id : 'UA-36138203-3'
  getclicky :
    site_id
